<!--
    This template file is for the SAML Attribute/Role Mapping settings.
    File acts as a view file for our attribute / role mapping page.
-->
<?php
    //Attribute mapping
    // initialze all values required to be shown on the page
    $roles = $this->getAllRoles();
    $groups = $this->getAllGroups();

    $isEnabled = $this->isEnabled();
    $disabled = !$isEnabled ? "disabled" : "";
    $sociallogin_am_username = $this->getUserNameMapping();
    $sociallogin_am_email = $this->getUserEmailMapping();
    $sociallogin_am_first_name = $this->getFirstNameMapping();
    $sociallogin_am_last_name = $this->getLastNameMapping();
    $sociallogin_am_table = $this->getTable();
    $sociallogin_am_country= $this->getCountryMapping();
    $sociallogin_am_company = $this->getCompanyMapping();
    $sociallogin_am_group_name = $this->getGroupMapping();

    $sociallogin_am_account_matcher = $this->getAccountMatcher();

    $emailSelected = $sociallogin_am_account_matcher == 'email' ? 'selected="selected"' : "";
    $usernameSelected = $sociallogin_am_account_matcher == 'username' ? 'selected="selected"' : "";

    $sociallogin_am_dont_allow_unlisted_user_role = $this->getDisallowUnlistedUserRole();
    $mo_sociallogin_dont_create_user_if_role_not_mapped = $this->getDisallowUserCreationIfRoleNotMapped();

    $default_role = $this->getDefaultRole();
    $formKey = $this->getFormKey();
    $premiumlink = $this->getExtensionPageUrl('upgrade');
?>
<div class="row">
<div class="col-sm-8">
    <div class="page" id="attrmapping">
        <div class="mosocial_table_layout">
           <form name="f" method="post" action="">
            <input type="hidden" name="form_key" value="<?php echo $escaper->escapeHtmlAttr($formKey); ?>" />
                <input type="hidden" name="option" value="saveAttrSettings">
                <h3>Attribute Mapping (Optional)</h3><hr>
                <table>
                    <tr>
                        <td colspan="2">
                            <div class="mo_note" style="width:130%;">
                                <span class="btn-link " >What is Attribute Mapping?</span>
                                <div  class ="premium_feature" style="display : inline-block">
                                <span style="color:red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*</span> (Available in the <a href="<?= $this->escapeUrl($premiumlink) ?>" 
                                class="premium btn-link">premium</a> version)</span>
                                </div>
                                <div style="display:none" class="show_info">
                                    <ol>
                                        <br>
                                        <li>Attributes are user details that are stored in your Identity Provider.</li>
                                        <li>Attribute Mapping helps you to get user attributes from your IdP and map them to
                                            Magento user attributes like firstname, lastname etc.</li>
                                        <li>While auto registering the users in your Magento site these attributes will automatically
                                            get mapped to your Magento user details.</li>
                                    </ol>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"><b>Users in Magento will be searched (existing Magento users) or created (new users) based
                         on the Email attribute.</td>
                    </tr>

                    <tr>
                        <td style="width:150px;"><strong>Username <span style="color:red;">*</span>:</strong></td>
                        <td><input type="text" name="sociallogin_am_username" placeholder="Enter attribute name for User Name"
                        value="<?= $this->escapeHtmlAttr($sociallogin_am_username) ?>"></td>
                    </tr>
                    <tr>
                        <td><strong>Email <span style="color:red;">*</span>:</strong></td>
                        <td><input type="text" name="sociallogin_am_email" placeholder="Enter attribute name for User Email"
                        value="<?= $this->escapeHtmlAttr($sociallogin_am_email) ?>">
                    </tr>
                    <tr>

                     <tr>
                        <td><strong>First Name:</strong></td>
                        <td><input type="text" name="saml_am_first_name" placeholder="Enter attribute name for First Name"
                            value="<?= $this->escapeHtmlAttr($sociallogin_am_first_name) ?>" disabled>
                    </tr>
                      <tr>
                        <td><strong>Last Name:</strong></td>
                        <td><input type="text" name="saml_am_last_name" placeholder="Enter attribute name for Last Name"
                            value="<?= $this->escapeHtmlAttr($sociallogin_am_last_name) ?>" disabled>
                    </tr>
                     <tr>
                       <td><strong>Country Name:</strong></td>
                       <td><input type="text" name="saml_am_country" placeholder="Enter attribute name for Country Name"
                           value="<?= $this->escapeHtmlAttr($sociallogin_am_country) ?>" disabled>
                   </tr>
                     <tr>
                      <td><strong>Company Name:</strong></td>
                      <td><input type="text" name="saml_am_company" placeholder="Enter attribute name for Company Name"
                          value="<?= $this->escapeHtmlAttr($sociallogin_am_company) ?>" disabled>
                  </tr>
                     <tr>
                        <td>&nbsp;</td>
                        <td><br ><input class="btn-round" type="submit" style="width:100px;" name="submit" value="Save"> &nbsp;
                        <br><br>
                        </td>
                    </tr>
                </table>
         </form>
      </div>
    </div>