<div class="row">
<div class="col-sm-8"> 
   <div class="page" id="samlsettings">
      <div class="mosp_table_layout">
         <h3>User Analytics Table:</h3>
         <hr>
         <form id="signInSettings" method="post" action="">
         <div class="mo_note">
                                <span class="btn-link" id="role_mapping" href="">What is User Analytics?</span>
                                 <div  class ="premium_feature" style="display : inline-block">
                                <span style="color:red">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp *</span> (Available in the <a href="<?php print_r($this->getExtensionPageUrl('upgrade')); ?>" 
                        class="premium btn-link">premium</a> version)</span>
                                </div>
                                <div style="display:none" class="show_info">
                                    <ol>
                                        <br>
                                        <li>Admins can see statistics of all configured social login platform. which will help admins to market their product in popular social platform</li>
                                        <li>User Analytics provides you with data of how many customer login via social which social platform, their number of order and number of item purchased.</li>
                                        <li>Also, Admins can find revenue generated of customer login via each platform.</li>
                                    </ol>
                                </div>
                            </div>

          <table class="test">
            <tr style="background-color:#C2C2C2">
                <td>Social media login of Customer</td>
                    <td>No. of Users logged in via social login</td>
                    <td>% Users logged in via social login</td>
                    <td>No. of created Users</td>
                    <td>% of created Users</td>
                    <td>Revenue</td>
                    <td>% Revenue</td>
            </tr>
            <tr>
                <td>Google</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>

            </tr>
            <tr>
                <td>Facebook</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>

            </tr>
            <tr>
                <td>LinkedIn</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>

            </tr>
            <tr>
                <td>Twitter</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>

            </tr>
            <tr style="background-color:#C2C2C2">
                <td>Total</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>

            </tr>
</table>
</form>
          </div>
          </div>
<style>
   .test td {
  border: 1px solid black;
}
    </style>