<!-- 
        This template shows a SSO link on the customer frontend pages 
        Use this if you want to show a sso link on your frontend pages
    -->
<?php
$enableGoogle = $this->getGoogleEnable();
$enableFacebook = $this->getGoogleEnable();
$enableLinkedin = $this->getGoogleLinkedin();
$enableTwitter = $this->getGoogleTwitter();
?>

<?php if ($enableGoogle == 1) : ?>
    <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForGoogle()) ?>"><span><?= $this->escapeHtml(__('Login with Google')) ?></span></a>
<?php endif; ?>
<?php if ($enableFacebook == 1) : ?>
    <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForFacebook()) ?>"><span><?= $this->escapeHtml(__('Login with Facebook')) ?></span></a>
<?php endif; ?>

<?php if ($enableLinkedin == 1) : ?>
    <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForLinkedin()) ?>"><span><?= $this->escapeHtml(__('Login with LinkedIn')) ?></span></a>
<?php endif; ?>

<?php if ($enableTwitter == 1) : ?>
    <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForTwitter()) ?>"><span><?= $this->escapeHtml(__('Login with Twitter')) ?></span></a>
<?php endif; ?>