<!-- 
    This template file is for the account settings.
    File acts as a view file for our Account.
-->

<?php
    // initialize all values required on this page
    $status = $block->getRegistrationStatus();
    $userEmail = $block->getCurrentAdminUser()->getEmail();    

echo '      <div class="row">
<div class="col-sm-8"> 
            <div class="page" id="account">		
            <div class="mosp_table_layout">' ; 

                if($status=='')
                {
                    echo  $block->getLayout()
                              ->createBlock("MiniOrange\TwoFA\Block\TwoFA")
                              ->setTemplate("MiniOrange_TwoFA::register.phtml")
                              ->toHtml() ;
                }
                else
                {
                    
                    echo  $block->getLayout()
                              ->createBlock("MiniOrange\TwoFA\Block\TwoFA")
                              ->setTemplate("MiniOrange_TwoFA::profile.phtml")
                              ->toHtml() ;
                }

echo '       </div>
        </div>' ;