<!--Pricing Tab-->
<?php

$idpsettings = $block->getExtensionPageUrl('idpsettings');
$hostname = $block->getMiniOrangeUrl();
$email = $block->getCustomerEmail();
$version = $block->getCurrentVersion();


echo '
     <div class="page" id="pricing" style=" border-radius: 20px; padding: 30px; margin : 20px;width:120%">

      <section class="pricing py-5">

      <div class="container">

      <div class="row"
      style="display:flex;"
      style="width:30%"
      >

        <!-- Free Tier -->
        <div class="columns">

              <ul class="price">

                <li class="header" style="background-color: #ea680b">2FA Free ' . $block->escapeHtmlAttr($version) . '</li>
                <li class="grey">$0</li>
                <li>&#10004 Authentication Methods (Limited Methods)</li>
                <li>&#10004 OTP Over SMS (10 SMS)</li>
                <li>&#10004 OTP Over Email (10 Email)</li>
                <li>&#10004 OTP Over SMS and Email (10 SMS & EMAIL)</li>
                <li>&#10004 Google Authenticator (10 Auto create user)</li>
                <li>&#10004 Allow specific 2fa methods to configure in inline registration</li>
                <li>&#10004 User management (reset users 2fa method)</li>
                <li>&#10004 Backdoor URL as Backup method for Backend Users</li>

                </ul>

            </div>
            <!-- Plus Tier -->
            <div class="columns">

            <ul class="price">

                       <li class="header" style="text-align:center">2FA-Backend </li>
                <li class="grey">$99</li>
         <li>&#10148; 15+ Authentication Methods</li>
           <li>&#10148; Allow specific 2fa methods to configure in inline registration</li>
           <li>&#10148; Email SMTP Custom Gateway</li>
           <li>&#10148; SMS Custom Gateway (Twilio/ Get Method/ Post Method)</li>
           <li>&#10148; Customize Email Templates</li>
           <li>&#10148; Customize SMS Templates</li>
           <li>&#10148; User management (reset users 2fa method)</li>
           <li>&#10148; Backend Role base 2fa</li>
           <li>&#10148; Backdoor URL as Backup method for Backend Users</li>
           <li>&#10148; Reconfigure/ change 2fa method for admin</li>
          
           <li style="text-align:center!important"><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+TwoFA+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+TwoFA+Premium+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a>
         </li>
          </ul>

        </div>


        <!-- Pro Tier -->
        <div class="columns">

        <ul class="price" >

               <li class="header" style="text-align:center">2FA-Frontend/Backend  </li>
                  <li class="grey">$299</li>
         <li>&#10148; <strong>All 2FA-Backend Features</strong></li>
           <li>&#10148; Set Different 2fa method for multiple sites.</li>
           <li>&#10148; Customer group/Role Based 2FA </li>
           <li>&#10148; Enforce 2fa at registration for customers</li>
           <li>&#10148; KBA as Backup method for Frontend Users</li>
           <li>&#10148; Customize Ui of login UI popup</li>
           <li>&#10148; Skip 2FA & Remember My Device</li>
           <li>&#10148; IP specific 2FA (Whitelisting IP Address)</li>
           <li>&#10148; Supports REST API to send and validate OTPs</li>
           
         <li style="text-align:center!important;margin-top:8px"><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+TwoFA+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+TwoFA+Premium+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a>
         </li>

           </ul>

         </div>
        
             </div>

             <div style="margin:2% 0 2% 2%;">

      <form style="display:none;" id="mocf_loginform" action="' . $block->escapeHtmlAttr($hostname) . '/moas/login"

          target="_blank" method="post">

          <input type="email" name="username" value="' . $block->escapeHtmlAttr($email) . '" >

          <input type="text" name="redirectUrl" value="' . $block->escapeHtmlAttr($hostname) . '/moas/initializepayment" >

          <input type="text" name="requestOrigin" id="requestOrigin"  >

      </form>

  </div>

    </div>


  </section>

    </div>

<div >
<p> Contact us at <a href="mailto:magentosupport@xecurify.com">magentosupport@xecurify.com</a> for more info.</p><br>

</div>

    ';