<!-- 
    This template shows a SSO box on the customer frontend pages
    Use this if you want to show a sso button on your frontend pages
-->
<?php
$enableGoogle = $this->getGoogleEnable();
$enableFacebook = $this->getFacebookEnable();
$enableLinkedin = $this->getLinkedinEnable();
$enableTwitter = $this->getTwitterEnable();
?>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<?php if ($enableGoogle == 1) : ?>
    <br>
    <div style="text-align:left;width:100%;">
        <div style="text-align:inline">
            <div style="width:489.3px">
                <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForGoogle()) ?>"
                   class="action login primary"
                   style="padding: 1% 14%; background-color: #dd4b39; border-radius:5px !important;">
                   <i class="fa fa-google" style="padding-top:0px !important; margin-top: 0"></i>
                   <span style="margin-left:50px;"><?= $this->escapeHtml(__('Login with Google')) ?></span>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($enableFacebook == 1) : ?>
    <br>
    <div style="width:450px">
        <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForFacebook()) ?>"
           class="action login primary"
           style="padding: 1% 14%; background-color:#3B5998; border-radius:5px !important;">
           <i class="fa fa-facebook" style="padding-top:0px !important; margin-top: 0"></i>
           <span style="margin-left:50px;"><?= $this->escapeHtml(__('Login with Facebook')) ?></span>
        </a>
    </div>
<?php endif; ?>

<?php if ($enableLinkedin == 1) : ?>
    <br>
    <div style="width:451.2px">
        <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForLinkedin()) ?>"
           class="action login primary"
           style="padding: 1% 14%; background-color:#007bb5; border-radius:5px !important;">
           <i class="fa fa-linkedin" style="padding-top:0px !important; margin-top: 0"></i>
           <span style="margin-left:50px;"><?= $this->escapeHtml(__('Login with LinkedIn')) ?></span>
        </a>
    </div>
<?php endif; ?>

<?php if ($enableTwitter == 1) : ?>
    <br>
    <div style="width:481.9px">
        <a href="<?= $this->escapeUrl($this->getSPInitiatedUrlForTwitter()) ?>"
           class="action login primary"
           style="padding: 1% 14%; background-color:#55ACEE; border-radius:5px !important;">
           <i class="fa fa-twitter" style="padding-top:0px !important; margin-top: 0"></i>
           <span style="margin-left:50px;"><?= $this->escapeHtml(__('Login with Twitter')) ?></span>
        </a>
    </div>
<?php endif; ?>