<!-- 
    This template file is for the sociallogin Attribute/Role Mapping settings.
    File acts as a view file for our attribute / role mapping page.
-->
<?php
    //Attribute mapping
    // initialze all values required to be shown on the page
    $roles = $this->getAllRoles();
    $groups = $this->getAllGroups();

    $isEnabled = $this->isEnabled();
    $disabled = !$isEnabled ? "disabled" : "";
    $sociallogin_am_username = $this->getUserNameMapping();
    $sociallogin_am_email = $this->getUserEmailMapping();
    $sociallogin_am_first_name = $this->getFirstNameMapping();
    $sociallogin_am_last_name = $this->getLastNameMapping();
    $sociallogin_am_group_name = $this->getGroupMapping();

    $sociallogin_am_account_matcher = $this->getAccountMatcher();

    $emailSelected = $sociallogin_am_account_matcher == 'email' ? 'selected="selected"' : "";
    $usernameSelected = $sociallogin_am_account_matcher == 'username' ? 'selected="selected"' : "";

    $sociallogin_am_dont_allow_unlisted_user_role = $this->getDisallowUnlistedUserRole();
    $mo_sociallogin_dont_create_user_if_role_not_mapped = $this->getDisallowUserCreationIfRoleNotMapped();

    
    $admin_roles_configured = $this->getRolesMapped();
    $customer_roles_configured = $this->getGroupsMapped();

    
    $default_role = $this->getDefaultRole();
    $formKey = $this->getFormKey();
    $premiumlink = $this->getExtensionPageUrl('upgrade');
?>
<div class="row">
<div class="col-sm-8">
    <div class="page" id="attrmapping">
        <div class="mosocial_table_layout">
            <form name="f" method="post" action="">
                <input type="hidden" name="form_key" value="<?php echo $escaper->escapeHtmlAttr($formKey); ?>" />
                <input type="hidden" name="option" value="saveAttrSettings">
                 <h3>Role Mapping (Optional)</h3><hr>  
                 
                <table>
                        <tr>
                        <td colspan="2">
                            <div class="mo_note">
                                <span class="btn-link" id="role_mapping" href="">What is Role Mapping?</span>
                                 <div  class ="premium_feature" style="display : inline-block">
                                <span style="color:red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*</span>(Available in the <a href="<?= $escaper->escapeUrl($premiumlink) ?>" 
                        class="premium btn-link">premium</a> version)</span>
                                </div>
                                <div style="display:none" class="show_info">
                                    <ol>
                                        <br>
                                        <li>Magento uses a concept of Roles, designed to give the site owner the ability to control 
                                                what users can and cannot do within the site.</li>
                                        <li>Role mapping helps you to assign specific roles to users of a certain group in your IdP.</li>
                                        <li>While auto registering, the users are assigned roles based on the group they are mapped to.</li>
                                    </ol>
                                </div>
                            </div>
                        </td>
                        </tr>
                    <tr><td colspan="2"><b>NOTE: </b> Group will be assigned only to non-admin users (user that do NOT have Administrator 
                        privileges). You will have to manually change the group of Administrator users.</td></tr>
                    <tr><td colspan="2"><input type="checkbox" id="dont_create_user_if_role_not_mapped" 
                        name="mo_sociallogin_dont_create_user_if_role_not_mapped" value="checked" 
                        <?= $escaper->escapeHtmlAttr($mo_sociallogin_dont_create_user_if_role_not_mapped) ?> disabled
                         >&nbsp;&nbsp;Do not auto create users if roles are not 
                        mapped here.</td></tr>
                    <tr><td colspan="2"><input type="checkbox" id="dont_allow_unlisted_user_role" 
                        name="sociallogin_am_dont_allow_unlisted_user_role" value="checked" 
                        <?= $escaper->escapeHtmlAttr($sociallogin_am_dont_allow_unlisted_user_role) ?> disabled>
                        &nbsp;&nbsp;Do not assign role to unlisted users.</td></tr>
                    <tr>
                        <td><strong>Default Role:</strong></td>
                        <td>
                                <select id="sociallogin_am_default_role" disabled name="sociallogin_am_default_role"
                                      style="width:150px;" >
<?php                                      

foreach ($roles as $role) {
    $selected = $default_role==$role['label']? 'selected' : '';
    echo '<option id="mo2f_roles"' . ($selected ? ' selected' : '') .
     ' name="' . $escaper->escapeHtmlAttr($role['label']) . '" value="' . $escaper->escapeHtmlAttr($role['label']) . '">' . 
     $escaper->escapeHtml($role['label']) . '</option>';
}
foreach ($groups as $group) {
    $selected = $default_role==$group['label']? 'selected' : '';
    echo '<option id="mo2f_roles"' . ($selected ? ' selected' : '') . ' name="' .
    $escaper->escapeHtmlAttr($group['label']) . '" value="' . $escaper->escapeHtmlAttr($group['label']) . '">' .
    $escaper->escapeHtml($group['label']) . '</option>';
}

echo'                           </select>
                            <i>Select the default role to assign to Backend Users.</i>
                        </td>
                    </tr>';


foreach ($roles as $role) {
    $role_value = $role['value'];
    $role_name = $role['label'];
                        
                        
    if (empty($admin_roles_configured)) {
        $admin_roles=[];
        $value = isset($admin_roles[$role_value]) ? $admin_roles[$role_value] : "";
    
    } else {
        $admin_roles = $admin_roles_configured ;
                            
        $value = isset($admin_roles[$role_value]) ? $admin_roles[$role_value] : "";
    
    }
    echo '<tr><td><b>' . $escaper->escapeHtml($role_name) . '</b></td><td><input type="text" name="sociallogin_am_admin_attr_values_' .
    $escaper->escapeHtmlAttr($role_value) . '" value="' . $escaper->escapeHtmlAttr($value) . '" placeholder="Semi-colon(;) separated Role value for ' .
    $escaper->escapeHtmlAttr($role_name) . '" style="width: 400px;" ' . $escaper->escapeHtmlAttr($disabled) . ' disabled></td></tr>';
}


                    echo '
                    <td></td>

                    <tr style="border-bottom: 1px solid #c1bdbd;">
                    <tr><td></td></tr>
                    <tr> 
                        <td><strong>Default Group:</strong></td>   
                        <td>    
                                <select id="saml_am_default_group" ' . $escaper->escapeHtmlAttr($disabled) . ' disabled="disabled" 
                                    name="saml_am_default_group" style="width:150px;">';
foreach ($groups as $group) {
    $selected = $default_role == $group['label'] ? 'selected="selected"' : '';
    echo '<option id="mo2f_roles" ' . ($default_role == $group['label'] ? 'selected="selected"' : '') . 
     ' value="' . $escaper->escapeHtmlAttr($group['label']) . '">' . 
     $escaper->escapeHtml($group['label']) . '</option>';
}
echo '                           </select>   
                            <i>Select the default group to assign to Frontend Users.</i> 
                        </td>   
                    </tr>';


if (empty($customer_roles_configured)) {
    $customer_fields = [];
} else {
    $customer_fields = [];
}
foreach ($groups as $group) {
    $role_value = $group['value'];
    $role_name = $group['label'];
    $value = isset($customer_fields[$role_value]) ? $customer_fields[$role_value] : "";
    echo '<tr><td><b>' . $escaper->escapeHtml($role_name) . '</b></td><td><input type="text" 
            name="sociallogin_am_group_attr_values_' . $escaper->escapeHtmlAttr($role_value) . '" 
            value="' . $escaper->escapeHtmlAttr($value) . '" 
            placeholder="Semi-colon(;) separated Group/Role value for ' . $escaper->escapeHtmlAttr($role_name) . '" 
            style="width: 400px;" ' . $escaper->escapeHtmlAttr($disabled) . ' disabled="disabled"></td></tr>';
}

echo '              <tr>
                        <td>&nbsp;</td>
                        <td><br><input type="submit" class="btn-round" style="width:100px;" 
                            name="submit" value="Save" ' . $escaper->escapeHtmlAttr($disabled) . '> &nbsp; 
                        <br><br>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>';